import { Product, Tenant } from '../types';

export const getStarterProductsForTenant = (tenant: Tenant): Product[] => {
  const isPetropolis = tenant.id === 'tenant-petropolis' || tenant.code.includes('PETROPOLIS');
  const isNiteroi = tenant.id === 'tenant-niteroi' || tenant.code.includes('NITEROI');

  if (isPetropolis) {
    return [
      {
        id: `p-petro-1`,
        tenantId: tenant.id,
        sku: 'PETRO-001',
        ean: '7898591450012',
        name: 'Fini Dentaduras 500g (Filial Petrópolis)',
        category: 'Balas de Gelatina',
        unit: 'Pacote 500g',
        stockDeposito: 45,
        stockLoja: 18,
        minStockDeposito: 20,
        minStockLoja: 8,
        costPrice: 12.50,
        sellPrice: 24.90,
        expirationDate: '2027-04-20',
        batchNumber: 'LOTE-PETRO-2026',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 180,
        totalSalesValue: 4482.00,
      },
      {
        id: `p-petro-2`,
        tenantId: tenant.id,
        sku: 'PETRO-002',
        ean: '7898591450029',
        name: 'Fini Bananas 500g (Filial Petrópolis)',
        category: 'Balas de Gelatina',
        unit: 'Pacote 500g',
        stockDeposito: 30,
        stockLoja: 15,
        minStockDeposito: 15,
        minStockLoja: 5,
        costPrice: 12.50,
        sellPrice: 24.90,
        expirationDate: '2027-05-10',
        batchNumber: 'LOTE-PETRO-B02',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 210,
        totalSalesValue: 5229.00,
      },
      {
        id: `p-petro-3`,
        tenantId: tenant.id,
        sku: 'PETRO-003',
        ean: '7898591450036',
        name: 'Fini Tubes Morango Azedinho 80g (Display 12un)',
        category: 'Regaliz & Tubes',
        unit: 'Display 12un',
        stockDeposito: 25,
        stockLoja: 10,
        minStockDeposito: 10,
        minStockLoja: 4,
        costPrice: 38.00,
        sellPrice: 72.00,
        expirationDate: '2027-03-15',
        batchNumber: 'LOTE-PETRO-T8',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 140,
        totalSalesValue: 10080.00,
      },
      {
        id: `p-petro-4`,
        tenantId: tenant.id,
        sku: 'PETRO-004',
        ean: '7898591450050',
        name: 'Fini Marshmallow Torção Vulcão 250g',
        category: 'Marshmallows',
        unit: 'Pacote 500g',
        stockDeposito: 40,
        stockLoja: 12,
        minStockDeposito: 15,
        minStockLoja: 5,
        costPrice: 11.20,
        sellPrice: 22.90,
        expirationDate: '2027-02-18',
        batchNumber: 'LOTE-PETRO-M01',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 160,
        totalSalesValue: 3664.00,
      }
    ];
  }

  if (isNiteroi) {
    return [
      {
        id: `p-nit-1`,
        tenantId: tenant.id,
        sku: 'NIT-001',
        ean: '7898591450043',
        name: 'Fini Minhocas Azedas 500g (Unidade Niterói)',
        category: 'Balas Azedas',
        unit: 'Pacote 500g',
        stockDeposito: 90,
        stockLoja: 35,
        minStockDeposito: 30,
        minStockLoja: 10,
        costPrice: 13.00,
        sellPrice: 25.90,
        expirationDate: '2027-06-30',
        batchNumber: 'LOTE-NIT-M99',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 410,
        totalSalesValue: 10619.00,
      },
      {
        id: `p-nit-2`,
        tenantId: tenant.id,
        sku: 'NIT-002',
        ean: '7898591450074',
        name: 'Fini Chiclete Salada de Frutas (Caixa 100un)',
        category: 'Chicletes',
        unit: 'Caixa 1kg',
        stockDeposito: 40,
        stockLoja: 18,
        minStockDeposito: 15,
        minStockLoja: 6,
        costPrice: 28.00,
        sellPrice: 55.00,
        expirationDate: '2027-08-10',
        batchNumber: 'LOTE-NIT-C10',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 280,
        totalSalesValue: 15400.00,
      },
      {
        id: `p-nit-3`,
        tenantId: tenant.id,
        sku: 'NIT-003',
        ean: '7898591450067',
        name: 'Fini Beijos de Morango 500g',
        category: 'Balas de Gelatina',
        unit: 'Pacote 500g',
        stockDeposito: 60,
        stockLoja: 22,
        minStockDeposito: 20,
        minStockLoja: 8,
        costPrice: 12.50,
        sellPrice: 24.90,
        expirationDate: '2027-07-15',
        batchNumber: 'LOTE-NIT-BJ',
        lastUpdated: new Date().toISOString(),
        totalSalesQuantity: 320,
        totalSalesValue: 7968.00,
      }
    ];
  }

  // Default Template for any new unit
  const slug = tenant.code.toLowerCase().replace(/[^a-z0-0]/g, '') || 'unit';
  return [
    {
      id: `p-${slug}-1`,
      tenantId: tenant.id,
      sku: `${tenant.code.slice(0, 4)}-001`,
      ean: '7898591450104',
      name: `Fini Ursinhos Brilho 100g (${tenant.name})`,
      category: 'Balas de Gelatina',
      unit: 'Pacote 100g',
      stockDeposito: 50,
      stockLoja: 20,
      minStockDeposito: 15,
      minStockLoja: 5,
      costPrice: 3.20,
      sellPrice: 6.90,
      expirationDate: '2027-09-01',
      batchNumber: `LOTE-${tenant.code}-01`,
      lastUpdated: new Date().toISOString(),
      totalSalesQuantity: 50,
      totalSalesValue: 345.00,
    },
    {
      id: `p-${slug}-2`,
      tenantId: tenant.id,
      sku: `${tenant.code.slice(0, 4)}-002`,
      ean: '7898591450012',
      name: `Fini Dentaduras 500g (${tenant.name})`,
      category: 'Balas de Gelatina',
      unit: 'Pacote 500g',
      stockDeposito: 35,
      stockLoja: 15,
      minStockDeposito: 10,
      minStockLoja: 5,
      costPrice: 12.50,
      sellPrice: 24.90,
      expirationDate: '2027-08-15',
      batchNumber: `LOTE-${tenant.code}-02`,
      lastUpdated: new Date().toISOString(),
      totalSalesQuantity: 30,
      totalSalesValue: 747.00,
    },
  ];
};
